version: 2
jobs:
  build:
    working_directory: ~/hrsf114-front-end-capstone
    docker:
      - image: circleci/node:10.0.0
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - run:
          name: install-dependencies
          command: 'npm install'
      - run:
          name: seed-database
          command: 'npm run seed'
      - run:
          name: run-tests
          command: 'npm test'
      - store_artifacts:
          path: test-results.xml
          prefix: test